# Generated by Django 5.1.7 on 2025-03-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blackjack", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suit",
                    models.CharField(
                        choices=[
                            ("H", "Hearts"),
                            ("D", "Diamonds"),
                            ("C", "Clubs"),
                            ("S", "Spades"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                            ("J", "Jack"),
                            ("Q", "Queen"),
                            ("K", "King"),
                            ("A", "Ace"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
