# Generated by Django 5.1.7 on 2025-03-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blackjack", "0003_delete_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="showed",
            field=models.BooleanField(default=False),
        ),
    ]
